#!/usr/bin/env bash

aux_port=${AUX_PORT:-7171}
#port=${1:-${PORT:-8080}}
port=${PORT:-8080}

if [ -z "$NGROK_API_TOKEN" ]; then
  echo "You must set the NGROK_API_TOKEN config var to create a TCP tunnel!"
  exit 1
fi

# Start the TCP tunnel
ngrok_cmd="bin/ngrok tcp -authtoken $NGROK_API_TOKEN -log stdout --log-level debug ${NGROK_OPTS} ${aux_port}"
echo "Starting ngrok with command \`${ngrok_cmd}\`"
eval "$ngrok_cmd | tee ngrok.log &"
ngrok_pid=$!

trap "kill $ngrok_pid" SIGTERM
trap "kill -9 $ngrok_pid; exit" SIGKILL

eval "ruby -rwebrick -e'WEBrick::HTTPServer.new(:BindAddress => \"0.0.0.0\", :Port => ${port}, :MimeTypes => {\"rhtml\" => \"text/html\"}, :DocumentRoot => Dir.pwd).start'"

eval "$@"